[workspace]
members = [
    "cli",
    "photonic",
    "meta",
    "http_server",
    "exiftool"
]
resolver = "2"
default-members = [
    "cli",
]

[workspace.package]
name = "photonic"
version = "0.0.1"
