[package]
name = "fotonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
chrono = { version = "0.4.26", features = ["serde"] }
derive_builder = "0.12.0"
derive_more = "0.99.17"
derive_setters = "0.1.6"
dotenv = "0.15.0"
env_logger = "0.10.0"
futures = "0.3.28"
infer = "0.15.0"
kamadak-exif = "0.5.5"
mime = "0.3.17"
mime_serde_shim = "0.2.2"
mongodb = { version = "2.6.1", features = ["bson-chrono-0_4"] }
once_cell = "1.18.0"
path-clean = "1.0.1"
regex = "1.9.1"
rexif = "0.7.3"
rexiv2 = "0.10.0"
serde = { version = "1.0.180", features = ["serde_derive", "derive"] }
serde_json = "1.0.104"
tokio = { version = "1.29.1", features = ["fs", "process", "io-util"] }
