services:
  server:
    image: photonic:latest
    env_file: ".env"
    ports:
      - "8080:8080"
    volumes:
      - photonic_data:/storage/
      - photonic_cache:/cache/
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    profiles:
      - develop
  db:
    image: postgres:16
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
volumes:
  photonic_data:
  photonic_cache:
  db_data:
