version: '3.4'

services:
  server:
    build:
      context: .
      target: final
    env_file: "./.env"
    ports:
      - "8080:8080"
  db:
    image: mongo:6.0
    env_file: "./.env"
    ports:
      - "27017:27017"
    volumes:
      - fotonic_data:/data/db
volumes:
  fotonic_data: