#@name Create with Heic
POST {{host}}/api/v1/medium
    ?filename=IMG_4598&extension=HEIC
Content-Type: image/heif

< ./test/data/IMG_4598.HEIC

###

#@name Create with RAW
POST {{host}}/api/v1/medium
    ?filename=IMG_4597&extension=DNG
Content-Type: image/dng

< ./test/data/IMG_4597.DNG

###
