use std::fmt::{Display, Formatter};

use kernel::error::{DomainResult, ValidationSnafu};
use serde::{Deserialize, Serialize};
use snafu::ensure;

/// Thumbnail variants generated by the client (Core Image/ImageIO) and
/// uploaded alongside the original. Each variant is constrained to fit
/// within a square of `max_dimension` pixels (longest edge).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThumbnailVariant {
    Tiny,
    Small,
    Large,
}

impl ThumbnailVariant {
    /// Maximum size (in pixels) of the longest edge for this variant.
    pub fn max_dimension(&self) -> u32 {
        match self {
            ThumbnailVariant::Tiny => 200,
            ThumbnailVariant::Small => 720,
            ThumbnailVariant::Large => 1440,
        }
    }

    /// Validates that the given dimensions fit within this variant's bounds.
    pub fn validate_dimensions(&self, width: u32, height: u32) -> DomainResult<()> {
        ensure!(
            width <= self.max_dimension() && height <= self.max_dimension(),
            ValidationSnafu {
                message: format!(
                    "Thumbnail dimensions {width}x{height} exceed the {:?} variant limit of {}px",
                    self,
                    self.max_dimension()
                ),
            }
        );
        Ok(())
    }

    /// Derives the variant an image belongs to from its actual dimensions:
    /// the smallest variant whose limit still covers the longest edge.
    /// Upload validation guarantees the image fits within its declared
    /// variant, so this reproduces the uploaded variant.
    pub fn from_dimensions(width: u32, height: u32) -> Self {
        let edge = width.max(height);
        [
            ThumbnailVariant::Tiny,
            ThumbnailVariant::Small,
            ThumbnailVariant::Large,
        ]
        .into_iter()
        .find(|v| v.max_dimension() >= edge)
        .unwrap_or(ThumbnailVariant::Large)
    }
}

impl Display for ThumbnailVariant {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            ThumbnailVariant::Tiny => write!(f, "tiny"),
            ThumbnailVariant::Small => write!(f, "small"),
            ThumbnailVariant::Large => write!(f, "large"),
        }
    }
}

impl std::str::FromStr for ThumbnailVariant {
    type Err = kernel::error::DomainError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "tiny" => Ok(ThumbnailVariant::Tiny),
            "small" => Ok(ThumbnailVariant::Small),
            "large" => Ok(ThumbnailVariant::Large),
            _ => Err(kernel::error::DomainError::Validation {
                message: format!(
                    "Invalid thumbnail variant '{s}', expected one of: tiny, small, large"
                ),
                backtrace: std::backtrace::Backtrace::capture(),
            }),
        }
    }
}

/// A 28-byte (approximate) perceptual placeholder hash computed from the
/// tiny thumbnail (evanw/thumbhash). Stored denormalized on the media row
/// for fast list queries.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Thumbhash(Vec<u8>);

impl Thumbhash {
    const MIN_LENGTH: usize = 4;
    const MAX_LENGTH: usize = 32;

    /// The thumbhash algorithm requires an input of at most 100x100 pixels;
    /// larger images are downscaled before hashing.
    const MAX_HASH_INPUT_DIMENSION: u32 = 100;

    pub fn new(bytes: Vec<u8>) -> kernel::error::DomainResult<Self> {
        ensure!(
            bytes.len() >= Self::MIN_LENGTH,
            kernel::error::ValidationSnafu {
                message: format!(
                    "Thumbhash must be at least {} bytes, got {}",
                    Self::MIN_LENGTH,
                    bytes.len()
                ),
            }
        );
        ensure!(
            bytes.len() <= Self::MAX_LENGTH,
            kernel::error::ValidationSnafu {
                message: format!(
                    "Thumbhash must be at most {} bytes, got {}",
                    Self::MAX_LENGTH,
                    bytes.len()
                ),
            }
        );
        Ok(Self(bytes))
    }

    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }

    pub fn into_inner(self) -> Vec<u8> {
        self.0
    }

    /// Computes the thumbhash from an encoded thumbnail image
    /// (JPEG/PNG/WebP). The image is decoded and downscaled to fit within
    /// 100x100 pixels before hashing, as required by the algorithm.
    pub fn compute(image_bytes: &[u8]) -> kernel::error::DomainResult<Self> {
        let img = image::load_from_memory(image_bytes).map_err(|e| {
            kernel::error::DomainError::Validation {
                message: format!("Failed to decode thumbnail image for thumbhash: {e}"),
                backtrace: std::backtrace::Backtrace::capture(),
            }
        })?;

        let thumb = if img.width().max(img.height()) > Self::MAX_HASH_INPUT_DIMENSION {
            img.thumbnail(
                Self::MAX_HASH_INPUT_DIMENSION,
                Self::MAX_HASH_INPUT_DIMENSION,
            )
        } else {
            img
        };

        let rgba = thumb.to_rgba8();
        let hash = thumbhash::rgba_to_thumb_hash(
            rgba.width() as usize,
            rgba.height() as usize,
            rgba.as_raw().as_slice(),
        );

        Thumbhash::new(hash)
    }
}

/// A thumbnail produced server-side by a [`ThumbnailGenerator`] port
/// implementation (e.g. a future libvips adapter for imports and directory
/// scanning).
#[derive(Debug, Clone)]
pub struct GeneratedThumbnail {
    pub variant: ThumbnailVariant,
    pub mime: mime::Mime,
    pub data: Vec<u8>,
    pub width: u32,
    pub height: u32,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn thumbnail_variant_max_dimensions() {
        assert_eq!(ThumbnailVariant::Tiny.max_dimension(), 200);
        assert_eq!(ThumbnailVariant::Small.max_dimension(), 720);
        assert_eq!(ThumbnailVariant::Large.max_dimension(), 1440);
    }

    #[test]
    fn thumbnail_variant_parse_valid() {
        assert_eq!(
            "tiny".parse::<ThumbnailVariant>().unwrap(),
            ThumbnailVariant::Tiny
        );
        assert_eq!(
            "small".parse::<ThumbnailVariant>().unwrap(),
            ThumbnailVariant::Small
        );
        assert_eq!(
            "large".parse::<ThumbnailVariant>().unwrap(),
            ThumbnailVariant::Large
        );
    }

    #[test]
    fn thumbnail_variant_parse_invalid() {
        assert!("huge".parse::<ThumbnailVariant>().is_err());
        assert!("".parse::<ThumbnailVariant>().is_err());
    }

    #[test]
    fn validate_dimensions_within_bounds() {
        assert!(ThumbnailVariant::Tiny.validate_dimensions(200, 200).is_ok());
        assert!(ThumbnailVariant::Small
            .validate_dimensions(720, 480)
            .is_ok());
        assert!(ThumbnailVariant::Large
            .validate_dimensions(1440, 1080)
            .is_ok());
    }

    #[test]
    fn validate_dimensions_exceeding_bounds() {
        assert!(ThumbnailVariant::Tiny
            .validate_dimensions(201, 100)
            .is_err());
        assert!(ThumbnailVariant::Small
            .validate_dimensions(721, 480)
            .is_err());
        assert!(ThumbnailVariant::Large
            .validate_dimensions(1441, 1080)
            .is_err());
    }

    #[test]
    fn from_dimensions_derives_variant() {
        assert_eq!(
            ThumbnailVariant::from_dimensions(150, 112),
            ThumbnailVariant::Tiny
        );
        assert_eq!(
            ThumbnailVariant::from_dimensions(200, 200),
            ThumbnailVariant::Tiny
        );
        assert_eq!(
            ThumbnailVariant::from_dimensions(600, 450),
            ThumbnailVariant::Small
        );
        assert_eq!(
            ThumbnailVariant::from_dimensions(720, 720),
            ThumbnailVariant::Small
        );
        assert_eq!(
            ThumbnailVariant::from_dimensions(1440, 1080),
            ThumbnailVariant::Large
        );
        assert_eq!(
            ThumbnailVariant::from_dimensions(4000, 3000),
            ThumbnailVariant::Large
        );
    }

    #[test]
    fn thumbhash_rejects_empty_and_oversized() {
        assert!(Thumbhash::new(vec![]).is_err());
        assert!(Thumbhash::new(vec![1, 2, 3]).is_err());
        assert!(Thumbhash::new(vec![0u8; 33]).is_err());
        assert!(Thumbhash::new(vec![1, 2, 3, 4]).is_ok());
    }

    #[test]
    fn compute_thumbhash_from_image() {
        let img = image::RgbaImage::from_pixel(80, 60, image::Rgba([120, 90, 60, 255]));
        let mut png = Vec::new();
        image::DynamicImage::ImageRgba8(img)
            .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
            .unwrap();

        let hash = Thumbhash::compute(&png).expect("thumbhash computation should succeed");
        assert!(!hash.as_bytes().is_empty());
        assert!(hash.as_bytes().len() <= 32);
    }

    #[test]
    fn compute_thumbhash_downscales_large_input() {
        // A 500x500 image exceeds the 100px thumbhash input limit and must
        // be downscaled rather than rejected.
        let img = image::RgbaImage::from_pixel(500, 500, image::Rgba([10, 200, 30, 255]));
        let mut jpeg = Vec::new();
        image::DynamicImage::ImageRgba8(img)
            .write_to(
                &mut std::io::Cursor::new(&mut jpeg),
                image::ImageFormat::Jpeg,
            )
            .unwrap();

        assert!(Thumbhash::compute(&jpeg).is_ok());
    }

    #[test]
    fn compute_thumbhash_rejects_garbage() {
        assert!(Thumbhash::compute(&[0xDE, 0xAD, 0xBE, 0xEF]).is_err());
    }
}
