[package]
name = "fotonic"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fotonic"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
http_server = { path = "../http_server" }
exiftool = { path = "../exiftool" }

clap = { version = "4.4.2", features = ["cargo"] }
dotenv = "0.15.0"
tokio = "1.32.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
