[package]
name = "fotonic"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fotonic"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
http_server = { path = "../http_server" }
exiftool = { path = "../exiftool" }

clap = { version = "4.4.2", features = ["cargo"] }
env_logger = "0.10.0"
actix-web = "4.4.0"
dotenv = "0.15.0"
log = "0.4.20"
tokio = "1.32.0"
