auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka:9094
    name: local
    properties: {}
    readOnly: false
    schemaRegistry: http://schema-registry:8081
rbac:
  roles: []
webclient: {}
