[package]
name = "http_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fotonic = { path = "../fotonic" }

chrono = { version = "0.4.33", features = ["serde"] }
env_logger = "0.11.1"
mime_serde_shim = "0.2.2"
serde = { version = "1.0.196", features = ["derive"] }
uuid = { version = "1.7.0", features = ["serde", "v8"] }
axum = { version = "0.7.4", features = ["query", "tracing"] }
hyper = "1.1.0"
tokio = { version = "1.36.0", features = ["signal"] }
tracing = "0.1.40"
tower-http = { version = "0.5.1", features = ["trace"] }
futures = "0.3.30"
tokio-util = "0.7.10"
axum-extra = { version = "0.9.2", features = ["typed-header"] }
snafu = "0.8.0"
mime = "0.3.17"
bson = "2.9.0"
jwt-authorizer = "0.14.0"
byte-unit = { version = "5.1.4", features = ["serde"] }
