[package]
name = "http_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.28", features = ["serde"] }
env_logger = "0.10.0"
core = { path = "../core" }
serde = { version = "1.0.188", features = ["derive"] }
uuid = { version = "1.4.1", features = ["serde", "v8"] }
axum = { version = "0.6.20", features = ["query", "tracing", "headers"] }
hyper = "0.14.27"
tokio = { version = "1.32.0", features = ["signal"] }
tracing = "0.1.37"
tower-http = { version = "0.4.4", features = ["trace"] }
