[package]
name = "http_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fotonic = { path = "../fotonic" }

chrono = { version = "0.4.31", features = ["serde"] }
env_logger = "0.10.1"
serde = { version = "1.0.195", features = ["derive"] }
uuid = { version = "1.6.1", features = ["serde", "v8"] }
axum = { version = "0.7.3", features = ["query", "tracing"] }
hyper = "1.1.0"
tokio = { version = "1.35.1", features = ["signal"] }
tracing = "0.1.40"
tower-http = { version = "0.5.0", features = ["trace"] }
futures = "0.3.30"
tokio-util = "0.7.10"
axum-extra = { version = "0.9.1", features = ["typed-header"] }
snafu = "0.8.0"
