@startuml
actor User
participant "Import" as import
participant "Metadata Extractor" as meta
participant "Storage" as store
database Filesystem as fs
queue EventStore as events
database KSQLDB as ksql

User -> import++: Upload image
import -> ksql++: Get current quota
return Quota
import -> import: Validate quota
opt Quota exceeded
    import --> User: 413 Quota exceeded
end opt
import -> fs++: Store image at temp path
return Saved
import ->> events: ImageUploadedEvent
return 201 (with ID)

events ->> ksql++: ImageUploadedEvent
ksql -> ksql--: Calculate new quota

events ->> meta++: ImageUploadedEvent
meta -> fs++: Extract metadata
return
meta ->> events--: MetadataSavedEvent

events ->> store++: MetadataSavedEvent
store -> store: Calculate new path
store -> fs++: Move image to new path
return
store ->> events--: ImageMovedEvent

@enduml
